### ISSUE TITLE
How Do I Change Stuff?

### ISSUE THREAD

**Issue by UkuleleBoy46** [nanite/Simple-Discord-Rich-Presence#25]
Hello, Sunekaer, I'm wondering how I change the images and things that show up on Discord. Can you please help me, I don't understand.
Thank you!

**Comment by MichaelHillcox** [comment]
Sorry, missed this, basically 90% of the config is on the side of the Discord app

See the following example:

![](https://c.mikey.pro/scr/M3uecYkX.png)

We have some predefined images we'll attempt to use:

- `menu` When the main menu is showing
- `loading` When the game is loading

After that, we either use the KubeJS integration:

```js
sdrp.dimension_change((event) => {
    const { player } = event;
    if (!player) {
      return;
    }

    if (!player.level) {
      return;
    }
    
    //                                     // Message (lang key), Image Name (the one you set in discord), Image Key (lang key)
    event.updateSDRPState("sdrp.team.in", "sdrp.team", "some_dimension_name");
});
```

![](https://c.mikey.pro/scr/ZCRKfFEQ.png)

Otherwise, we'll attempt to set it automatically based on the dimensions name:

- Name: `sdrp.[DIMENSION_NAME]` (Language key)
- Image Key: `sdrp.[DIMENSION_NAME].in`
- Image Name: `[DIMESNION_NAME]`

So for this to work, you'd need to have an image added to your Discord apps rich presents settings under the name of the dimension you want to support.

If I wanted to support the end and the overworld for example. Their names are as follows `minecraft:overworld`, `minecraft:the_end`. We ignore the `minecraft:` part and name the images `the_end` and `overworld`. We then add a language key to the language Json for both the `Image Key` and `Name`:

```json
{
  "sdrp.overworld": "Overworld",
  "sdrp.overworld.in": "In the Overworld"
}
``` 

We support all of these without the need for doing anything more than adding the images to your application on Discord

![](https://c.mikey.pro/scr/aB7bNrcD.png)

**Comment by UkuleleBoy46** [comment]
Oh, I see! Thank you.
